apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: go-web-app.local      # Replace with your domain or use an IP address
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golang-app
            port:
              number: 80
  # Optional: TLS configuration for HTTPS
  tls:
  - hosts:
    - go-web-app.local          # Replace with your domain
    secretName: tls-secret     # Reference to a secret containing your TLS certs
