apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Optional: Rewrite URLs if needed
spec:
  rules:
  - host: your-domain.com  # Replace with your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golang-app
            port:
              number: 80
