name: CI/CD

on:
  push:
    branches:
    - main
    paths-ignore:
      - 'helm/**'
      - 'manifest/**'
      - 'README.md'
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go 1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22

            - name: Build the Golang image   
              run: go build -o golang-app

            - name: Test the golang app
              run: go test -v -cover ./...
